name: tickets
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.6.18
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  flutter_toggle_tab: ^1.4.1
  fluttertoast: ^8.2.3
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  http: ^1.1.0
  http_parser: ^4.0.2
  image_picker: ^1.0.4
  intl: ^0.18.1
  json_annotation: ^4.8.1
  kakao_flutter_sdk_user: ^1.6.1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  stacked_card_carousel: ^0.0.4
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cats/
    - assets/categories/
    - assets/icons/
    - assets/terms/
    - assets/tickets/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.ttf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/font/SUIT-Light.ttf
          weight: 300
        - asset: assets/font/SUIT-Regular.ttf
          weight: 400
        - asset: assets/font/SUIT-Medium.ttf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/font/SUIT-Bold.ttf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/font/SUIT-Heavy.ttf
          weight: 900
