name: tickets
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.6.18
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  get: ^4.6.6
  kakao_flutter_sdk_user: ^1.6.1
  permission_handler: ^11.0.1
  the_apple_sign_in: ^1.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/terms/

  fonts:
    - family: SUIT
      fonts:
        - asset: assets/font/SUIT-Thin.ttf
          weight: 100
        - asset: assets/font/SUIT-ExtraLight.ttf
          weight: 200
        - asset: assets/font/SUIT-Light.ttf
          weight: 300
        - asset: assets/font/SUIT-Regular.ttf
          weight: 400
        - asset: assets/font/SUIT-Medium.ttf
          weight: 500
        - asset: assets/font/SUIT-SemiBold.ttf
          weight: 600
        - asset: assets/font/SUIT-Bold.ttf
          weight: 700
        - asset: assets/font/SUIT-ExtraBold.ttf
          weight: 800
        - asset: assets/font/SUIT-Heavy.ttf
          weight: 900
